# Generated by Django 5.1.11 on 2025-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('tasks', 'Tasks'), ('roadmap', 'Roadmap')], max_length=20),
        ),
    ]
