# Generated by Django 5.1.11 on 2025-09-06 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_board_board_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('game_unity', 'Game - Unity'), ('game_ue', 'Game - UE'), ('game_other', 'Game - Other'), ('plugin', 'Plugin'), ('mod', 'Mod'), ('discord_bot', 'Discord Bot'), ('software', 'Software'), ('webapp', 'Web/Webapp')], db_index=True, default='software', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='planning', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='projects_pr_project_573ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'project_type'], name='projects_pr_status_b41d0a_idx'),
        ),
    ]
