# Generated by Django 5.1.11 on 2025-09-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['project', 'joined_at']},
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='role',
        ),
    ]
