# Generated by Django 5.1.11 on 2025-09-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmembership_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
