# Generated by Django 5.1.11 on 2025-09-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_type_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('game_unity', 'Game - Unity'), ('game_ue', 'Game - UE'), ('game_other', 'Game - Other'), ('plugin', 'Plugin'), ('mod', 'Mod'), ('mcmod', 'Minecraft Mod'), ('discord_bot', 'Discord Bot'), ('software', 'Software'), ('webapp', 'Web/Webapp')], db_index=True, default='software', max_length=20),
        ),
    ]
