# Generated by Django 5.1.11 on 2025-09-07 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'is_roadmap_item'], name='projects_ta_project_45eab2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'project'], name='projects_ta_assigne_697e10_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['column', 'position'], name='projects_ta_column__ae5292_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='projects_ta_created_b3975c_idx'),
        ),
    ]
