# Generated by Django 5.1.11 on 2025-09-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_projects_ta_project_45eab2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['project', 'position'], name='projects_pr_project_6255d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'title'), name='uniq_project_link_title')],
            },
        ),
    ]
