# Generated by Django 5.1.11 on 2025-09-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('pm', 'Project Manager'), ('dev', 'Developer')], db_index=True, default='dev', max_length=8),
        ),
    ]
