# Generated by Django 5.1.11 on 2025-09-07 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetcatalog', '0001_initial'),
        ('projects', '0005_task_projects_ta_project_45eab2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetproject',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['created_at'], name='assetcatalo_created_c4bd70_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['created_by', 'created_at'], name='assetcatalo_created_850995_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetproject',
            constraint=models.UniqueConstraint(fields=('asset', 'project'), name='assetproject_unique_asset_project'),
        ),
    ]
