# Generated by Django 5.1.11 on 2025-09-07 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kb/attachments/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, help_text='For anonymous feedback tracking', max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('link_type', models.CharField(choices=[('documentation', 'Documentation'), ('tutorial', 'Tutorial'), ('reference', 'Reference'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['link_type', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='articleassetlink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articleassetlink',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='articleassetlink',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleassetlink',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='articleprojectlink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articleprojectlink',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='articleprojectlink',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleprojectlink',
            name='project',
        ),
        migrations.RemoveField(
            model_name='articleprojectlink',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-is_pinned', '-is_featured', '-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'ordering': ['position', '-uploaded_at']},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='kb_article_status_018a76_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='estimated_reading_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='article',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=160),
        ),
        migrations.AddField(
            model_name='article',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Optional icon class (e.g., 'book', 'code', 'gear')", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='Brief summary for search results and previews', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, db_index=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='kb_article_status_730390_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', 'status'], name='kb_article_is_feat_a7746b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_pinned', 'status'], name='kb_article_is_pinn_0118e0_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='kb_category_is_acti_018dd4_idx'),
        ),
        migrations.AddField(
            model_name='articleattachment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kb.article'),
        ),
        migrations.AddField(
            model_name='articleattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlefeedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='kb.article'),
        ),
        migrations.AddField(
            model_name='articlefeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='kb.article'),
        ),
        migrations.DeleteModel(
            name='ArticleAssetLink',
        ),
        migrations.DeleteModel(
            name='ArticleProjectLink',
        ),
        migrations.AlterUniqueTogether(
            name='articlefeedback',
            unique_together={('article', 'session_key'), ('article', 'user')},
        ),
    ]
